name: Padel Automation

on:
  schedule:
    - cron: '0 8 * * 1' # Ejecuta todos los lunes a las 08:00 AM UTC
  workflow_dispatch:   # Esto activa un bot√≥n para que puedas probarlo YA

jobs:
  run-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: pip install discord.py requests beautifulsoup4 python-dotenv gspread oauth2client
      - name: Update Discord
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          GUILD_ID: ${{ secrets.GUILD_ID }}
          ID_CANAL_LOGS: ${{ secrets.ID_CANAL_LOGS }}
        run: python main.py
      - name: Update Google Sheets
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python ranking.py